import Foundation

public enum SpeciesFlavorText {
    public static let byID: [String: String] = [
        "GRS_001": "Mossbun nibbles dew-bright shoots and vanishes into clover when startled.",
        "GRS_002": "Pebblequail is often spotted where fresh grass bends in neat little paths.",
        "GRS_003": "Seedkit prefers soft moss beds and keeps seed caches under low roots.",
        "GRS_004": "Fernfawn nibbles dew-bright shoots and vanishes into clover when startled.",
        "GRS_005": "Sprigmouse is often spotted where fresh grass bends in neat little paths.",
        "GRS_006": "Pollenpup prefers soft moss beds and keeps seed caches under low roots.",
        "GRS_007": "Twiglet nibbles dew-bright shoots and vanishes into clover when startled.",
        "GRS_008": "Acornip is often spotted where fresh grass bends in neat little paths.",
        "GRS_009": "Clovercub prefers soft moss beds and keeps seed caches under low roots.",
        "GRS_010": "Bramblefinch nibbles dew-bright shoots and vanishes into clover when startled.",
        "GRS_011": "Brushfox keeps to taller reeds, weaving through stems before anyone gets close.",
        "GRS_012": "Cloverboar appears where the grove grows dense and the air smells freshly cut.",
        "GRS_013": "Reedram follows hidden trails through brush and only pauses where petals gather.",
        "GRS_014": "Sapstoat keeps to taller reeds, weaving through stems before anyone gets close.",
        "GRS_015": "Tanglemole appears where the grove grows dense and the air smells freshly cut.",
        "GRS_016": "Bloomhare follows hidden trails through brush and only pauses where petals gather.",
        "GRS_017": "Barkbat keeps to taller reeds, weaving through stems before anyone gets close.",
        "GRS_018": "Petalynx appears where the grove grows dense and the air smells freshly cut.",
        "GRS_019": "Loamguin follows hidden trails through brush and only pauses where petals gather.",
        "GRS_020": "Vinekip keeps to taller reeds, weaving through stems before anyone gets close.",
        "GRS_021": "Thornlynx patrols old root paths and is said to appear when the meadow feels restless.",
        "GRS_022": "Grovehart leaves clawed tracks in bark and never lingers in the same clearing twice.",
        "GRS_023": "Canopuma is drawn to wind-shaken canopies and the sharp scent of split thorns.",
        "GRS_024": "Briarbuck patrols old root paths and is said to appear when the meadow feels restless.",
        "GRS_025": "Rootwing leaves clawed tracks in bark and never lingers in the same clearing twice.",
        "GRS_026": "Mossmane is drawn to wind-shaken canopies and the sharp scent of split thorns.",
        "GRS_027": "Wildbloom patrols old root paths and is said to appear when the meadow feels restless.",
        "GRS_028": "Verdhound leaves clawed tracks in bark and never lingers in the same clearing twice.",
        "GRS_029": "Elderstag is treated like a guardian of the deep grove, emerging when the whole field seems to breathe.",
        "GRS_030": "Bloomdrake bends branches around itself as if the forest were making room for a sovereign guest.",
        "GRS_031": "Crownelk crosses the oldest parts of the field with the weight of a living seasonal omen.",
        "GRS_032": "Solbriar is treated like a guardian of the deep grove, emerging when the whole field seems to breathe.",
        "GRS_033": "Verdant Wyvern bends branches around itself as if the forest were making room for a sovereign guest.",
        "GRS_034": "Bloomwarden crosses the oldest parts of the field with the weight of a living seasonal omen.",
        "GRS_035": "Verdant Kirin is spoken of as a world-tree omen, leaving the grassland brighter long after it passes.",
        "GRS_036": "Worldroot Seraph appears only in impossible stillness, when every blade seems to bow toward it.",
        "GRS_037": "Sunseed Levi is remembered less as an animal and more as a visitation from the living grove.",
        "GRS_038": "Evergreen Sovereign is spoken of as a world-tree omen, leaving the grassland brighter long after it passes.",
        "SKY_001": "Puffowl rides gentle drafts and dips low whenever warm air gathers above open ground.",
        "SKY_002": "Kitemoth drifts through bright cloud edges in loose little spirals before darting away.",
        "SKY_003": "Breezesparrow spends most of the day chasing tiny thermal pockets across the sky field.",
        "SKY_004": "Driftbat rides gentle drafts and dips low whenever warm air gathers above open ground.",
        "SKY_005": "Cirrofinch drifts through bright cloud edges in loose little spirals before darting away.",
        "SKY_006": "Cloudlet spends most of the day chasing tiny thermal pockets across the sky field.",
        "SKY_007": "Gustling rides gentle drafts and dips low whenever warm air gathers above open ground.",
        "SKY_008": "Flittern drifts through bright cloud edges in loose little spirals before darting away.",
        "SKY_009": "Hushkite spends most of the day chasing tiny thermal pockets across the sky field.",
        "SKY_010": "Skydart rides gentle drafts and dips low whenever warm air gathers above open ground.",
        "SKY_011": "Galefinch circles the higher currents and only descends when the wind begins to tighten.",
        "SKY_012": "Nimbusray slips between cloud bands with a practiced glide that is hard to follow from below.",
        "SKY_013": "Zephyhare favors storm-light horizons where the air tastes sharp and electric.",
        "SKY_014": "Aerowisp circles the higher currents and only descends when the wind begins to tighten.",
        "SKY_015": "Glideroo slips between cloud bands with a practiced glide that is hard to follow from below.",
        "SKY_016": "Stormlark favors storm-light horizons where the air tastes sharp and electric.",
        "SKY_017": "Nimbuscat circles the higher currents and only descends when the wind begins to tighten.",
        "SKY_018": "Kestrelot slips between cloud bands with a practiced glide that is hard to follow from below.",
        "SKY_019": "Vaporwing favors storm-light horizons where the air tastes sharp and electric.",
        "SKY_020": "Swoopcub circles the higher currents and only descends when the wind begins to tighten.",
        "SKY_021": "Stormheron appears where pressure shifts suddenly, cutting through the field like a warning line.",
        "SKY_022": "Skyviper hunts along violent updrafts and vanishes before the clouds settle again.",
        "SKY_023": "Tempestail is said to draw a cleaner path through the sky than the wind itself.",
        "SKY_024": "Windserpent appears where pressure shifts suddenly, cutting through the field like a warning line.",
        "SKY_025": "Galehart hunts along violent updrafts and vanishes before the clouds settle again.",
        "SKY_026": "Hailjack is said to draw a cleaner path through the sky than the wind itself.",
        "SKY_027": "Stratosfang appears where pressure shifts suddenly, cutting through the field like a warning line.",
        "SKY_028": "Cloudmantis hunts along violent updrafts and vanishes before the clouds settle again.",
        "SKY_029": "Halo Roc arrives with cathedral-scale calm, hovering as if the entire sky were arranged around it.",
        "SKY_030": "Dawnalbat glows through stormbreak light and turns rough air into a silent corridor.",
        "SKY_031": "Prismwing passes overhead like a migrating constellation that briefly takes wing.",
        "SKY_032": "Cyclonarch arrives with cathedral-scale calm, hovering as if the entire sky were arranged around it.",
        "SKY_033": "Starfeather glows through stormbreak light and turns rough air into a silent corridor.",
        "SKY_034": "Skylight Seraph passes overhead like a migrating constellation that briefly takes wing.",
        "SKY_035": "Aurora Seraphowl is treated as a celestial sign, appearing when the upper air looks too luminous to be real.",
        "SKY_036": "Celestalon leaves the field in reverent silence, as though even thunder has stepped back.",
        "SKY_037": "Firmament Wyrm is remembered as a sky-born revelation more than a creature of feather or scale.",
        "SKY_038": "Horizon Phoenix is treated as a celestial sign, appearing when the upper air looks too luminous to be real.",
        "CST_001": "Foamcrab follows the foam line and darts between shells before the next wave arrives.",
        "CST_002": "Shellpup appears where the tide leaves bright pools and the sand is still cool.",
        "CST_003": "Driftminnow scavenges along the shoreline and always seems to know where the sea will break next.",
        "CST_004": "Tideling follows the foam line and darts between shells before the next wave arrives.",
        "CST_005": "Coralmouse appears where the tide leaves bright pools and the sand is still cool.",
        "CST_006": "Brinekit scavenges along the shoreline and always seems to know where the sea will break next.",
        "CST_007": "Pebbleclam follows the foam line and darts between shells before the next wave arrives.",
        "CST_008": "Surftern appears where the tide leaves bright pools and the sand is still cool.",
        "CST_009": "Ripplepup scavenges along the shoreline and always seems to know where the sea will break next.",
        "CST_010": "Kelpfin follows the foam line and darts between shells before the next wave arrives.",
        "CST_011": "Driftotter lingers near reefs and shallow channels, surfacing only when the water turns glassy.",
        "CST_012": "Coralwhisk moves with the pull of the tide and keeps close to stones polished by salt.",
        "CST_013": "Wavehog prefers the edge between surf and still water, where the coast never fully settles.",
        "CST_014": "Marinaff lingers near reefs and shallow channels, surfacing only when the water turns glassy.",
        "CST_015": "Saltstoat moves with the pull of the tide and keeps close to stones polished by salt.",
        "CST_016": "Reefrunner prefers the edge between surf and still water, where the coast never fully settles.",
        "CST_017": "Pearlmink lingers near reefs and shallow channels, surfacing only when the water turns glassy.",
        "CST_018": "Tidehopper moves with the pull of the tide and keeps close to stones polished by salt.",
        "CST_019": "Harborseal prefers the edge between surf and still water, where the coast never fully settles.",
        "CST_020": "Spraytail lingers near reefs and shallow channels, surfacing only when the water turns glassy.",
        "CST_021": "Tidefang hunts the darker water beyond the break, then slips inland on sudden spray.",
        "CST_022": "Ripturtle is tied to rip currents and moon-drawn tides that most shoreline creatures avoid.",
        "CST_023": "Reefstalker shows itself when the whole coast starts to feel heavy with hidden motion.",
        "CST_024": "Brinehorn hunts the darker water beyond the break, then slips inland on sudden spray.",
        "CST_025": "Currentcobra is tied to rip currents and moon-drawn tides that most shoreline creatures avoid.",
        "CST_026": "Duskdolph shows itself when the whole coast starts to feel heavy with hidden motion.",
        "CST_027": "Seaflare hunts the darker water beyond the break, then slips inland on sudden spray.",
        "CST_028": "Gullfang is tied to rip currents and moon-drawn tides that most shoreline creatures avoid.",
        "CST_029": "Moonfin Levi rises like a local legend from below the surf, carrying the glow of deep water with it.",
        "CST_030": "Coral Regent is greeted like old royalty by the coast, with waves seeming to crest around its route.",
        "CST_031": "Maelstrom Eel turns rough tide into ceremony, leaving a wake that looks almost deliberate.",
        "CST_032": "Tidemaw rises like a local legend from below the surf, carrying the glow of deep water with it.",
        "CST_033": "Luminray is greeted like old royalty by the coast, with waves seeming to crest around its route.",
        "CST_034": "Abyssnarwhal turns rough tide into ceremony, leaving a wake that looks almost deliberate.",
        "CST_035": "Abyss Pearlwyrm is spoken of as a trench-born myth, seen only when sea and sky feel impossibly wide.",
        "CST_036": "Trench Sovereign leaves pearl-bright memories in every account, no matter how brief the sighting was.",
        "CST_037": "Ocean Halo Whale is less a coastal animal than a sovereign event pulled in from the abyss.",
        "CST_038": "Stormtide Basilisk is spoken of as a trench-born myth, seen only when sea and sky feel impossibly wide.",
        "ICE_001": "Snowmole scurries across packed snow shelves and settles wherever the ice stays quiet.",
        "ICE_002": "Glintbeet appears near wind-carved ridges where loose powder still skims across the crust.",
        "ICE_003": "Driftpup favors pale drifts lit by blue ice and vanishes the moment the field goes still.",
        "ICE_004": "Icemouse scurries across packed snow shelves and settles wherever the ice stays quiet.",
        "ICE_005": "Snowrat appears near wind-carved ridges where loose powder still skims across the crust.",
        "ICE_006": "Crystalbug favors pale drifts lit by blue ice and vanishes the moment the field goes still.",
        "ICE_007": "Sleetstoat scurries across packed snow shelves and settles wherever the ice stays quiet.",
        "ICE_008": "Hailhopper appears near wind-carved ridges where loose powder still skims across the crust.",
        "ICE_009": "Snowbat favors pale drifts lit by blue ice and vanishes the moment the field goes still.",
        "ICE_010": "Iceslug scurries across packed snow shelves and settles wherever the ice stays quiet.",
        "ICE_011": "Glintferret moves through snow gullies with the confidence of something born to whiteout light.",
        "ICE_012": "Hailtoad keeps close to blue-ice cracks and glassy shelves where the field turns colder by the minute.",
        "ICE_013": "Snowbadger is usually found where windblown snow, crystal flakes, and hard ice gather in the same pocket.",
        "ICE_014": "Glaciercat moves through snow gullies with the confidence of something born to whiteout light.",
        "ICE_015": "Snowlark keeps close to blue-ice cracks and glassy shelves where the field turns colder by the minute.",
        "ICE_016": "Crystalmole is usually found where windblown snow, crystal flakes, and hard ice gather in the same pocket.",
        "ICE_017": "Shardhog moves through snow gullies with the confidence of something born to whiteout light.",
        "ICE_018": "Shardrat keeps close to blue-ice cracks and glassy shelves where the field turns colder by the minute.",
        "ICE_019": "Hailwren is usually found where windblown snow, crystal flakes, and hard ice gather in the same pocket.",
        "ICE_020": "Glaciercub moves through snow gullies with the confidence of something born to whiteout light.",
        "ICE_021": "Aurora Lynx travels the deeper ice seams and leaves the snow shelf scored where it passed.",
        "ICE_022": "Bergmole appears when old pressure wakes the glacier and the whole field starts to sing.",
        "ICE_023": "Icemaw is drawn to clear blue ice, buried light, and echoing snow caverns.",
        "ICE_024": "Glacier Ram travels the deeper ice seams and leaves the snow shelf scored where it passed.",
        "ICE_025": "Snowfang appears when old pressure wakes the glacier and the whole field starts to sing.",
        "ICE_026": "Crystaladder is drawn to clear blue ice, buried light, and echoing snow caverns.",
        "ICE_027": "Snowburrow travels the deeper ice seams and leaves the snow shelf scored where it passed.",
        "ICE_028": "Glacier Hydra appears when old pressure wakes the glacier and the whole field starts to sing.",
        "ICE_029": "Whiteout Wyrm advances like a stormfront given form, with the whole ice field reshaping around it.",
        "ICE_030": "Hail Coloss is treated like an ancient winter guardian whose route is older than the snow shelf itself.",
        "ICE_031": "Glacier Drake seems to wake the whole glacier, scattering ice-light and crystal dust in its path.",
        "ICE_032": "Aurora Chimera advances like a stormfront given form, with the whole ice field reshaping around it.",
        "ICE_033": "Crystal Molem is treated like an ancient winter guardian whose route is older than the snow shelf itself.",
        "ICE_034": "Ice Basilisk seems to wake the whole glacier, scattering ice-light and crystal dust in its path.",
        "ICE_035": "Polarcore Golem is whispered about as the living core of the polar field, too immense to belong to ordinary winter.",
        "ICE_036": "Aurora Drake is seen only under impossible skyglow, when blue ice starts reflecting colors no dawn should hold.",
        "ICE_037": "Whiteout Titan feels less discovered than revealed, as though the storm briefly stepped aside to show its heart.",
    ]
}
